services:
  # Backend API
  - type: web
    name: nike-backend
    runtime: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: DATABASE_NAME
        value: Nike
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: PYTHON_VERSION
        value: 3.11.0
